replicaCount: 3

image:
  repository: gcr.io/google-samples/hello-app
  tag: "2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "32Mi"
    cpu: "20m"
  limits:
    memory: "128Mi"
    cpu: "200m"